import type { Metadata } from "next";
import { Audiowide } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/nav/top-nav";
import { ClerkProvider } from "@clerk/nextjs";
import { VideoProvider } from "@/context/video";
import PayPalProvider from "@/context/paypal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const audiowide = Audiowide({
  variable: "--font-audiowide",
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className={`${audiowide.variable} antialiased`}>
          <VideoProvider>
            <PayPalProvider>
              <TopNav />
              {children}
            </PayPalProvider>
          </VideoProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
